000100001027CRTMSGF &LIB/ARSMESSAGE
000200001027             ADDMSGD    MSGID(ARS0001) MSGF(&LIB/ARSMESSAGE) +
000300001027                          MSG('This is the first level text') +
000400001027                          SECLVL('this is the second level test')
000500001027             ADDMSGD    MSGID(ARS0002) MSGF(&LIB/ARSMESSAGE) +
000600001027                          MSG('This is the first level text') +
000700001027                          SECLVL('this is the second level test')
